version: "3"
services:
  runner:
    hostname: runner
    build: .
    ports:
      - "5002:5002"
    privileged: true
    restart: always

networks:
  default:
    external:
      name: proxy-network